In [1]:
import pandas as pd
import geopandas as gpd
from os import path, makedirs

from core.downloads.geosampa import get_capabilities, get_features

# Mapa 06 - Área de parques por subprefeitura

Esse notebook é responsável pelo download dos dados utilizados no dashboard https://datasp.observatorio.tcm.sp.gov.br/urbanismo#area-de-parques-municipais-e-estaduais-2024 do DataSP. No ano de 2025 os dados foram obtidos manualmente, mas em 2026 serão obtidos via script para os anos de referência de 2024 e 2025.

# Extração dos dados

## Subprefeituras

In [2]:
get_capabilities(filter="subp")

[{'name': 'geoportal:GEOSAMPA_v_praca_largo',
  'title': 'Cadastro de Praças e Largos',
  'abstract': 'Localização das praças e largos no território do município de São Paulo, com base nas informações repassadas por subprefeituras, SF e SEGES/CGPATRI.'},
 {'name': 'geoportal:perimetro_zoneamento_revogado_lei13885',
  'title': 'Perímetro Zona de Uso - Revogado - Lei 13.885/04',
  'abstract': 'A Lei de Zoneamento estabelece normas complementares ao Plano Diretor Estratégico, institui os Planos Regionais Estratégicos das Subprefeituras, dispõe sobre o parcelamento, disciplina e ordena o Uso e Ocupação do Solo do Município de São Paulo. Os perímetros de zona de uso foram vetorizados perante o estabelecido na Lei nº 13.885/2004, tendo como base cartográfica o Mapa Digital da Cidade (MDC).'},
 {'name': 'geoportal:sede_subprefeitura',
  'title': 'Subprefeituras',
  'abstract': 'Localização das sedes físicas das Subprefeituras da Cidade de São Paulo.'},
 {'name': 'geoportal:subprefeitura',
  'title': 'Subprefeituras',
  'abstract': 'As subprefeituras foram criadas mediante a Lei nº 13.339/2002. Seus limites foram estabelecidos de forma a não comprometer a divisão distrital do município, permitindo assim a agregação de dados também para cada uma dessas unidades político-administrativas.'},
 {'name': 'geoportal:zoneamento_corredor_uso',
  'title': 'Zona de Centralidade Linear - Revogado - Lei 13.885/04',
  'abstract': 'Os Corredores de uso são trechos de logradouros públicos enquadrados como zonas de centralidades, complementam o zoneamento do território da cidade de São Paulo. A Lei de Zoneamento estabelece normas complementares ao Plano Diretor Estratégico, institui os Planos Regionais Estratégicos das Subprefeituras, dispõe sobre o parcelamento, disciplina e ordena o Uso e Ocupação do Solo do Município de São Paulo. Os corredores de uso foram vetorizados de acordo com o estabelecido na Lei nº 13.885/2004, tendo como base cartográfica o Mapa Digital da Cidade (MDC).'},
 {'name': 'geoportal:lote_cidadao',
  'title': 'lote_cidadao',
  'abstract': 'Lotes fiscais com informações de zoneamento. A Lei de Zoneamento estabelece normas complementares ao Plano Diretor Estratégico, institui os Planos Regionais Estratégicos das Subprefeituras, dispõe sobre o parcelamento, disciplina e ordena o Uso e Ocupação do Solo do Município de São Paulo. Os valores de zoneamento, estabelecido na Lei nº 13.885/2004, foram agregados as feições de lotes através dos números de setor, quadra e lote , tendo como base cartográfica o Mapa Digital da Cidade e as informações fiscais da Secretaria de Finanças.'}]

In [3]:
subprefeituras = get_features("geoportal:subprefeitura")
subprefeituras

,id,cd_identificador_subprefeitura,cd_subprefeitura,nm_subprefeitura,tx_escala,sg_fonte_original,dt_criacao,cd_tipo_discrepancia,dt_atualizacao,cd_usuario_atualizacao,sg_subprefeitura,qt_area_quilometro,qt_area_metro,cd_regiao_05,nm_regiao_05,cd_regiao_08,nm_regiao_08,geometry
0,subprefeitura.1,1,02,PIRITUBA-JARAGUA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.387000+00:00,,PJ,55,5.502102e+07,3,Norte,4,Norte 2,"POLYGON ((318663.925 7404127.712, 318663.251 7..."
1,subprefeitura.2,2,03,FREGUESIA-BRASILANDIA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.389000+00:00,,FO,32,3.198020e+07,3,Norte,4,Norte 2,"POLYGON ((327340.628 7399133.313, 327331.514 7..."
2,subprefeitura.3,3,04,CASA VERDE-LIMAO-CACHOEIRINHA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.362000+00:00,,CV,27,2.723234e+07,3,Norte,4,Norte 2,"POLYGON ((329084.795 7402363.669, 329086.123 7..."
3,subprefeitura.4,4,05,SANTANA-TUCURUVI,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.395000+00:00,,ST,36,3.578252e+07,3,Norte,5,Norte 1,"POLYGON ((334076.366 7398045.594, 334074.986 7..."
4,subprefeitura.5,5,06,JACANA-TREMEMBE,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.360000+00:00,,JT,65,6.511566e+07,3,Norte,5,Norte 1,"POLYGON ((335167.648 7404409.048, 335167.247 7..."
5,subprefeitura.6,6,07,VILA MARIA-VILA GUILHERME,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.396000+00:00,,MG,27,2.689922e+07,3,Norte,5,Norte 1,"POLYGON ((336762.078 7401144.267, 336794.867 7..."
6,subprefeitura.7,7,21,PENHA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.391000+00:00,,PE,40,4.042924e+07,2,Leste,2,Leste 1,"POLYGON ((346801.065 7402842.892, 346800.103 7..."
7,subprefeitura.8,8,22,ERMELINO MATARAZZO,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.398000+00:00,,EM,16,1.596639e+07,2,Leste,3,Leste 2,"POLYGON ((349116.316 7399473.221, 349133.905 7..."
8,subprefeitura.9,9,23,SAO MIGUEL,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.358000+00:00,,MP,26,2.615923e+07,2,Leste,3,Leste 2,"POLYGON ((352480.323 7397515.871, 352477.052 7..."
9,subprefeitura.10,10,24,ITAIM PAULISTA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.366000+00:00,,IT,22,2.160382e+07,2,Leste,3,Leste 2,"POLYGON ((356423.064 7397223.44, 356418.471 73..."
10,subprefeitura.11,11,27,ITAQUERA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.371000+00:00,,IQ,55,5.512913e+07,2,Leste,3,Leste 2,"POLYGON ((353782.483 7397480.849, 353783.234 7..."
11,subprefeitura.12,12,28,GUAIANASES,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.349000+00:00,,GU,18,1.777556e+07,2,Leste,3,Leste 2,"POLYGON ((354697.574 7396050.701, 354696.418 7..."
12,subprefeitura.13,13,08,LAPA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.345000+00:00,,LA,41,4.063870e+07,4,Oeste,6,Oeste,"POLYGON ((321633.729 7393535.365, 321633.031 7..."
13,subprefeitura.14,14,09,SE,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.369000+00:00,,SE,27,2.666547e+07,1,Centro,1,Centro,"POLYGON ((330197.017 7396087.885, 330211.849 7..."
14,subprefeitura.15,15,25,MOOCA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.342000+00:00,,MO,36,3.604691e+07,2,Leste,2,Leste 1,"POLYGON ((334126.109 7396389.068, 334125.831 7..."
15,subprefeitura.16,16,26,ARICANDUVA-FORMOSA-CARRAO,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.393000+00:00,,AF,22,2.233572e+07,2,Leste,2,Leste 1,"POLYGON ((341388.453 7394169.562, 341389.571 7..."
16,subprefeitura.17,17,30,SAO MATEUS,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.373000+00:00,,SM,45,4.531114e+07,2,Leste,3,Leste 2,"POLYGON ((348628.153 7386651.573, 348630.82 73..."
17,subprefeitura.18,18,29,VILA PRUDENTE,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.381000+00:00,,VP,19,1.919989e+07,2,Leste,2,Leste 1,"POLYGON ((338848.335 7388663.606, 338840.448 7..."
18,subprefeitura.19,19,13,IPIRANGA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.344000+00:00,,IP,37,3.749732e+07,5,Sul,7,Sul 1,"POLYGON ((335254.612 7391150.376, 335253.982 7..."
19,subprefeitura.20,20,12,VILA MARIANA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.378000+00:00,,VM,27,2.698441e+07,5,Sul,7,Sul 1,"POLYGON ((332031.435 7385561.331, 332030.94 73..."
20,subprefeitura.21,21,10,BUTANTA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.368000+00:00,,BT,56,5.630516e+07,4,Oeste,6,Oeste,"POLYGON ((320567.464 7394377.312, 320581.184 7..."
21,subprefeitura.22,22,11,PINHEIROS,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.383000+00:00,,PI,32,3.199353e+07,4,Oeste,6,Oeste,"POLYGON ((327871.085 7386152.364, 327865.295 7..."
22,subprefeitura.23,23,17,CAMPO LIMPO,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.364000+00:00,,CL,37,3.667387e+07,5,Sul,8,Sul 2,"POLYGON ((321584.417 7387081.364, 321600.008 7..."
23,subprefeitura.24,24,18,M BOI MIRIM,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.340000+00:00,,MB,62,6.241139e+07,5,Sul,8,Sul 2,"POLYGON ((316695.723 7378199.471, 316704.833 7..."
24,subprefeitura.25,25,19,CAPELA DO SOCORRO,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.400000+00:00,,CS,133,1.328440e+08,5,Sul,8,Sul 2,"POLYGON ((324231.68 7377883.648, 324086.906 73..."
25,subprefeitura.26,26,16,CIDADE ADEMAR,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.317000+00:00,,AD,31,3.081024e+07,5,Sul,8,Sul 2,"POLYGON ((332383.832 7381216.079, 332408.532 7..."
26,subprefeitura.27,27,20,PARELHEIROS,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.385000+00:00,,PA,361,3.606542e+08,5,Sul,8,Sul 2,"POLYGON ((319909.103 7371860.127, 320004.091 7..."
27,subprefeitura.28,28,15,JABAQUARA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.347000+00:00,,JA,14,1.400981e+07,5,Sul,7,Sul 1,"POLYGON ((331544.24 7384735.403, 331562.36 738..."
28,subprefeitura.29,29,14,SANTO AMARO,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.353000+00:00,,SA,38,3.774532e+07,5,Sul,8,Sul 2,"POLYGON ((327892.375 7386141.134, 327896.575 7..."
29,subprefeitura.30,30,31,CIDADE TIRADENTES,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.377000+00:00,,CT,15,1.493904e+07,2,Leste,3,Leste 2,"POLYGON ((357428.688 7387653.528, 357433.497 7..."
30,subprefeitura.31,31,01,PERUS-ANHANGUERA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.375000+00:00,,PR,57,5.688931e+07,3,Norte,4,Norte 2,"POLYGON ((325464.932 7409329.344, 325464.513 7..."
31,subprefeitura.32,32,32,SAPOPEMBA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.356000+00:00,,SB,14,1.363290e+07,2,Leste,2,Leste 1,"POLYGON ((344641.98 7387700.637, 344641.228 73..."

## Parques

In [4]:
get_capabilities(filter="parque")

[{'name': 'geoportal:pde_estrategia_desenvolvimento_economico',
  'title': 'Estratégias de Desenvolvimento Econômico',
  'abstract': 'Estratégias de Desenvolvimento Econômico, considerando os PEDEs, Polo de Economia Criativa e Parque Tecnológico.'},
 {'name': 'geoportal:pde_parque_municipal',
  'title': 'Parques Municipais (Mapa 5)',
  'abstract': 'Mapa 5 - Parques Municipais Existentes e Propostos.'},
 {'name': 'geoportal:GEOSAMPA_cadparcs_parque_unidade_conservacao',
  'title': 'Parques e Unidades de Conservação',
  'abstract': ''},
 {'name': 'geoportal:iluminacao_publica',
  'title': 'Pontos de iluminação pública',
  'abstract': 'Postes de iluminação pública localizados no sistema viário, praças, áreas públicas municipais, parques municipais, áreas internas de próprios municipais. A quantidade de e o tipo de iluminação são baseadas em informações de levantamento cadastral realizado pela Secretaria de Serviços através do Departamento de Iluminação Pública - ILUME.'},
 {'name': 'geoportal:pde2014_v_parq_pde_map',
  'title': 'Áreas Verdes (5)',
  'abstract': 'Rede Hídrica Ambiental e Sistema de Áreas Protegidas, Áreas Verdes e Espaços Livres:\r\nO Sistema de Áreas Protegidas, Áreas Verdes e Espaços Livres é constituído pelo conjunto de áreas enquadradas nas diversas categorias protegidas pela legislação ambiental, de terras indígenas, de áreas prestadoras de serviços ambientais, das diversas tipologias de parques de logradouros públicos, de espaços vegetados e de espaços não ocupados por edificação coberta, de propriedade pública ou particular.'}]

In [5]:
parques = get_features("geoportal:GEOSAMPA_cadparcs_parque_unidade_conservacao")
parques

,id,cd_identificador_cadparcs_parque_unidade_conservacao,nm_area,tx_tipo_categoria,tx_data_inauguracao,tx_instrumento_legal_criacao,tx_situacao,nm_administrador,qt_area_metro,cd_pde_2022,geometry
0,cadparcs_parque_unidade_conservacao.356,356,Novo Pinheiros - Bruno Covas,Parque Linear,2022,Res. SMA 74/14,Parque - Estado,SEMIL/CPP,1369265.90,None,"MULTIPOLYGON (((323985.099 7383986.592, 323984..."
1,cadparcs_parque_unidade_conservacao.364,364,Morro Grande,Parque Urbano,Proposto (estudo fundiario DUP 62.497/23),None,Proposto - outros,None,535775.30,PQ_FO_06,"MULTIPOLYGON (((325727.288 7403303.07, 325721...."
2,cadparcs_parque_unidade_conservacao.285,285,Corrego Itaquera,Parque Linear,2024,None,Parque - outra secretaria,SMSUB,25327.26,None,"MULTIPOLYGON (((355998.317 7391884.436, 355998..."
3,cadparcs_parque_unidade_conservacao.329,329,Banespa,Parque Urbano,Proposto (estudo fundiario DUP 64.511/25),None,Proposto - outros,None,62318.00,None,"MULTIPOLYGON (((327581.125 7385464.867, 327581..."
4,cadparcs_parque_unidade_conservacao.45,45,Sape,Parque Linear,2009,None,Parque - SVMA,SVMA/CGPABI/DGPU,34380.74,PQ_BT_16,"MULTIPOLYGON (((320729.853 7390900.271, 320739..."
...,...,...,...,...,...,...,...,...,...,...,...
371,cadparcs_parque_unidade_conservacao.190,190,Aricanduva,Parque Linear,Proposto (área gerida por SVMA),Dec. 53.510/12 e Dec. 56.868/16,Proposto - imovel SVMA,SVMA/CGPABI/DGPU,3786.97,PQ_AF_04,"MULTIPOLYGON (((341946.918 7396183.512, 341937..."
372,cadparcs_parque_unidade_conservacao.20,20,Alto Da Boa Vista,Parque Urbano,2021,Dec. 44.206/03 e Dec. 44.926/04,Parque - SVMA,SVMA/CGPABI/DGPU,48307.05,PQ_SA_06,"MULTIPOLYGON (((327620.703 7383796.21, 327632...."
373,cadparcs_parque_unidade_conservacao.44,44,Casa Modernista,Parque Urbano,2010,None,Parque - SVMA,SVMA/CGPABI/DGPU,12682.74,PQ_VM_02,"MULTIPOLYGON (((333382.346 7389587.105, 333385..."
374,cadparcs_parque_unidade_conservacao.323,323,Anhanguera,Parque Urbano,1979,None,Parque - SVMA,SVMA/CGPABI/DGPU,1812501.90,PQ_PR_01.1,"MULTIPOLYGON (((317551.626 7408971.653, 317558..."
375,cadparcs_parque_unidade_conservacao.378,378,Itaguacu,Parque Urbano,Proposto (área gerida por SVMA),Dec. 44.404/04,Proposto - imovel SVMA,SVMA/CGPABI/DGPU,229036.30,PQ_CV_06,"MULTIPOLYGON (((329246.955 7405771.371, 329256..."

# Exportando os arquivos

Neste notebook, vamos apenas salvar os arquivos extraídos na pasta de entrada de dados.

In [6]:
output_dir = path.join('data', 'cache', 'urbanismo')

if not path.exists(output_dir):
    makedirs(output_dir)

for c, gdf in [('subprefeituras', subprefeituras),
               ('parques', parques),
               ]:
    filename=path.join(output_dir, c)
    gdf.to_file(f'{filename}.gpkg', layer=c, driver='GPKG')